"""
One source of truth for every number the prose quotes.

The April 2026 draft carried 80 hand-typed decimal numbers, and several were
wrong: a standard error of 4.8 where the code produced 7.45, an out-of-sample
table matching no estimator in the repository, Friday counts from a different
sample period. Every one of those errors was a transcription, not an analysis
mistake.

The remedy is that analysis code registers a value once, under a name, and
every consumer reads the name. `write` emits a LaTeX macro file the manuscript
inputs and a JSON file the prose checker uses. Nothing downstream retypes a
digit.

Usage:

    from src.numbers import record, write

    record("EffectRegression", 17.61, "{:.2f}",
           "Paper spec, stacked album-days, CR1 by album")
    ...
    write()

In the manuscript:

    \\input{../tabs/_numbers}
    We estimate \\numEffectRegression{} excess deaths.
"""

import json
from pathlib import Path

TABS_DIR = Path(__file__).parent.parent / "tabs"

_REGISTRY = {}


def record(name, value, fmt="{:.2f}", note=""):
    """
    Register one number under a name.

    `name` must be CamelCase with no digits or underscores, because it becomes
    a LaTeX control sequence. Re-registering a name with a different value is
    an error: two call sites disagreeing about one quantity is the bug this
    module exists to prevent.
    """
    if not name.isalpha():
        raise ValueError(
            f"{name!r} is not usable as a LaTeX macro name; use letters only"
        )

    formatted = fmt.format(value)
    if name in _REGISTRY and _REGISTRY[name]["formatted"] != formatted:
        raise ValueError(
            f"{name!r} already recorded as {_REGISTRY[name]['formatted']}, "
            f"now {formatted}. Two call sites disagree about one quantity."
        )

    _REGISTRY[name] = {"value": float(value), "formatted": formatted, "note": note}
    return value


def write(tabs_dir=None):
    """Emit tabs/_numbers.tex and tabs/_numbers.json. Returns the registry."""
    tabs_dir = Path(tabs_dir or TABS_DIR)

    lines = [
        "% Generated by src/numbers.py. Do not edit.",
        "% Every number the manuscript quotes is defined here exactly once.",
        "",
    ]
    for name in sorted(_REGISTRY):
        entry = _REGISTRY[name]
        if entry["note"]:
            lines.append(f"% {entry['note']}")
        lines.append(f"\\newcommand{{\\num{name}}}{{{entry['formatted']}}}")
    (tabs_dir / "_numbers.tex").write_text("\n".join(lines) + "\n")

    (tabs_dir / "_numbers.json").write_text(json.dumps(_REGISTRY, indent=2) + "\n")

    print(f"\n  Wrote {len(_REGISTRY)} named numbers to tabs/_numbers.{{tex,json}}")
    return _REGISTRY


def registry():
    """The registry, for tests and for the prose checker."""
    return dict(_REGISTRY)
